name: Other
description: Something else? if the options above do not suit
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, take a moment to search through the current open ones.

        ---

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: "Describe"
    validations:
      required: true
